[versions]
agp = "8.13.1"
androidLibrary = "8.12.1"
codeScanner = "2.3.0"
commonsNet = "3.6"
dexter = "6.2.3"
escposThermalprinterAndroid = "3.2.0"
eventbus = "3.3.1"
expandableFab = "1.1.1"
firebaseCrashlytics = "19.1.0"
firebaseDatabase = "21.0.0"
firebaseConfig = "22.0.0"
firebaseMessaging = "24.0.1"
flexbox = "3.0.0"
glide = "4.16.0"
googleMapsServices = "2.2.0"
gson = "2.10.1"
io = "7.0.2"
kotlin = "2.0.21"
coreKtx = "1.17.0"
junit = "4.13.2"
junitVersion = "1.3.0"
espressoCore = "3.7.0"
appcompat = "1.7.1"
loggingInterceptor = "4.9.1"
material = "1.13.0"
activity = "1.10.1"
constraintlayout = "2.2.1"
mpandroidchart = "v3.1.0"
okhttp = "4.10.0"
photoview = "2.3.0"
picasso = "2.8"
places = "4.0.0"
playServicesLocation = "21.3.0"
playServicesMaps = "19.0.0"
retrofit = "2.9.0"
swiperefreshlayout = "1.2.0-alpha01"
googleAndroidLibrariesMapsplatformSecretsGradlePlugin = "2.0.1"
googleGmsGoogleServices = "4.4.2"
googleFirebaseCrashlytics = "3.0.3"
media3Player = "1.8.0"
media3Ui = "1.8.0"

[libraries]
androidx-core-ktx = { group = "androidx.core", name = "core-ktx", version.ref = "coreKtx" }
androidx-swiperefreshlayout = { module = "androidx.swiperefreshlayout:swiperefreshlayout", version.ref = "swiperefreshlayout" }
code-scanner = { module = "com.github.yuriy-budiyev:code-scanner", version.ref = "codeScanner" }
commons-net = { module = "commons-net:commons-net", version.ref = "commonsNet" }
converter-gson = { module = "com.squareup.retrofit2:converter-gson", version.ref = "retrofit" }
dexter = { module = "com.karumi:dexter", version.ref = "dexter" }
escpos-thermalprinter-android = { module = "com.github.DantSu:ESCPOS-ThermalPrinter-Android", version.ref = "escposThermalprinterAndroid" }
eventbus = { module = "org.greenrobot:eventbus", version.ref = "eventbus" }
expandable-fab = { module = "com.nambimobile.widgets:expandable-fab", version.ref = "expandableFab" }
firebase-config = { module = "com.google.firebase:firebase-config", version.ref = "firebaseConfig" }
firebase-crashlytics = { module = "com.google.firebase:firebase-crashlytics", version.ref = "firebaseCrashlytics" }
firebase-database = { module = "com.google.firebase:firebase-database", version.ref = "firebaseDatabase" }
firebase-messaging = { module = "com.google.firebase:firebase-messaging", version.ref = "firebaseMessaging" }
flexbox = { module = "com.google.android.flexbox:flexbox", version.ref = "flexbox" }
glide = { module = "com.github.bumptech.glide:glide", version.ref = "glide" }
google-maps-services = { module = "com.google.maps:google-maps-services", version.ref = "googleMapsServices" }
gson = { module = "com.google.code.gson:gson", version.ref = "gson" }
io = { module = "com.itextpdf:io", version.ref = "io" }
junit = { group = "junit", name = "junit", version.ref = "junit" }
androidx-junit = { group = "androidx.test.ext", name = "junit", version.ref = "junitVersion" }
androidx-espresso-core = { group = "androidx.test.espresso", name = "espresso-core", version.ref = "espressoCore" }
androidx-appcompat = { group = "androidx.appcompat", name = "appcompat", version.ref = "appcompat" }
kernel = { module = "com.itextpdf:kernel", version.ref = "io" }
layout = { module = "com.itextpdf:layout", version.ref = "io" }
logging-interceptor = { module = "com.squareup.okhttp3:logging-interceptor", version.ref = "loggingInterceptor" }
material = { group = "com.google.android.material", name = "material", version.ref = "material" }
androidx-activity = { group = "androidx.activity", name = "activity", version.ref = "activity" }
androidx-constraintlayout = { group = "androidx.constraintlayout", name = "constraintlayout", version.ref = "constraintlayout" }
mpandroidchart = { module = "com.github.PhilJay:MPAndroidChart", version.ref = "mpandroidchart" }
okhttp = { module = "com.squareup.okhttp3:okhttp", version.ref = "okhttp" }
photoview = { module = "com.github.chrisbanes:PhotoView", version.ref = "photoview" }
picasso = { module = "com.squareup.picasso:picasso", version.ref = "picasso" }
places = { module = "com.google.android.libraries.places:places", version.ref = "places" }
play-services-maps = { module = "com.google.android.gms:play-services-maps", version.ref = "playServicesMaps" }
play-services-location = { module = "com.google.android.gms:play-services-location", version.ref = "playServicesLocation" }
retrofit = { module = "com.squareup.retrofit2:retrofit", version.ref = "retrofit" }
media3-exoplayer = { module = "androidx.media3:media3-exoplayer", version.ref = "media3Player" }
media3-ui = { module = "androidx.media3:media3-ui", version.ref = "media3Ui" }

[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }
android-library = { id = "com.android.library", version.ref = "androidLibrary" }
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
google-android-libraries-mapsplatform-secrets-gradle-plugin = { id = "com.google.android.libraries.mapsplatform.secrets-gradle-plugin", version.ref = "googleAndroidLibrariesMapsplatformSecretsGradlePlugin" }
google-gms-google-services = { id = "com.google.gms.google-services", version.ref = "googleGmsGoogleServices" }
google-firebase-crashlytics = { id = "com.google.firebase.crashlytics", version.ref = "googleFirebaseCrashlytics" }

